### ISSUE TITLE
midterm-jpark.py ready for grading

### ISSUE THREAD

**Issue by bmiller11-matc** [madisoncollege-it-programs/python-scripting-bmiller11-matc#10]

**Comment by cethenmc** [comment]
Midterm-jpark:   Thanks for putting in an effort on this part of the midterm.  The first part I analyze is program execution.  When I enter false username and password combos three times, the third failure should only render the magic word clause 25 times.  You keep the single occurrence with the counter firing on that last one (1 pt).  In the code, the username and password were not set inside a dictionary as requested (2 pts).  On line 24, recall a print function does not have a return value, as such, saving that statement to a keys variable will not have anything in it (2 pts), and when you print out the keys variable in your formatted string it returns [None].  Nice job setting the input to a variable, so that it could be used in your flow logic.  The flow, however, uses hardcoded values when the three main choices could be consolidated and pulled directly from the dictionary in the same if statement.  Separating the three means every single one fires even when the first is satisfied (1 pt).  The breaks were inserted to compensate for not using white_rabbit_object as requested in the requirements (1 pts).  26/33
