### ISSUE TITLE
week 14 my-json.py ready for grading

### ISSUE THREAD

**Issue by bmiller11-matc** [madisoncollege-it-programs/python-scripting-bmiller11-matc#15]

**Comment by cethenmc** [comment]
Hi, Brianna.  You need to review arparse, especially before the final.  You got it working using sysargv, so that was nice to see.  However, the requirement was to use argparse.  I could tell after I issued my first command (./my-json.py) in the picture below that you used sysargv based on the error.  **I will grant a 5 out of 8 for now, but please resubmit soon using argparse to get full credit.**  Also add the author and short description in comments toward the top of the script.  This should be your standard operating procedure.

![image](https://user-images.githubusercontent.com/112707666/205675363-038b2ea7-db14-43f3-a93c-adca3574c8ab.png)

**Comment by cethenmc** [comment]
![image](https://user-images.githubusercontent.com/112707666/208516708-cb468b1a-59fe-4d1f-90ce-259a306d8a2a.png)
