### ISSUE TITLE
final exam ready for grading

### ISSUE THREAD

**Issue by bmiller11-matc** [madisoncollege-it-programs/python-scripting-bmiller11-matc#16]

**Comment by cethenmc** [comment]
Hi, Brianna.  You chose to use sys.argv instead of argparse.  As a result, you switched something where order did not matter, to where order mattered.  For example, if done with argparse, I could have executed the following successfully:

./final-exam.py -q 4 -s [www.py.land](http://www.py.land/)

Using sysargv like you did, you build the wrong URL.

Also, Function 4 was the only one which executes without an accompanying error.  The rest gave this error:


Going against the scoring checklist, you scored a 62 out of 100, securinga 'C' in the course.  Thank you for being part of the class, and best wishes on your future courses.

Main script
	• Unnecessary print of arg on line 14 (-1 point)
	• Built URL with sys.argv instead of argparse.  (-1 point) 
	• No elifs, so ifs execute every time regardless of which function is run.  (-1 point)
	• Processed each code set representing each function with the "if" after it, so again all pseudo-functions run every time (-5 points)
	• Answer did not match the picture for each of the functions (except for 4)  (-4 points)
Function 1
	• No function definition and no return (-2 point) 
	• Because you chose to use 'content' instead of 'text' it came out as a bytearray that needed a decode() (-1 point) 
	• Gives an error (-1 point)
Function 2
	• No function definition and no return (-2 point)
	• Forgot to slice to pull out the words 'Hidden Message' (-1 point)
	• No loop required to pull 'h3' taglessly; could have capitalized on BeautifulSoup to do in a single line. (-1 point)
	• Gives an error (-1 point)
Function 3
	• No function definition and no return (-2 point)
	• Gives an error (-1 point)
Function 4
	• No function definition and no return (-2 point)
Function 5
	• No function definition and no return (-2 point)
	• Gives an error (-1 point)
	• To include port 6200 in your scan, the range needed to end with 6201 (-1 point)
	• No timeout set to prevent waiting  (-1 point)  
	• No connect with host and port (-1 point)
	• No try/except block (-1 point)
	• Port # not appended to the RCV data to separate open from closed (-1 point) 
	• No received data being captured (and no decode, as a result (-2 points)
	• Port number not appended, but printed directly (-1 point)
	• Socket close missing (-1 point)

**Comment by cethenmc** [comment]
What I referred to, as the accompanying error:

![image](https://user-images.githubusercontent.com/112707666/208516650-5fa237a0-b71d-43ca-b4b9-08c635ea45d4.png)
