### ISSUE TITLE
Week 5 3 files ready for grading

### ISSUE THREAD

**Issue by bmiller11-matc** [madisoncollege-it-programs/python-scripting-bmiller11-matc#4]

**Comment by cethenmc** [comment]
In week 5, I am seeking files.py.  I don't see that.  There should only be one file that does all 3 parts.  Please resubmit.

**Comment by cethenmc** [comment]
Hi, Brianna.  I am more than happy to help.  If you would like to book time with me, please go to Instructor Contact in Blackboard, and book time.  If none of the times are available, please share other times, and I will try to find a mutually agreeable time for a Teams call.  Thanks.  ~Chris

**Comment by bmiller11-matc** [comment]
file resubmitted

**Comment by cethenmc** [comment]
Hi Brianna. Thanks for turning around your corrections so quickly.  I will record a 4 of 8 on this assignment for now (until corrected), but I definitely think it would be good for us to meet on this one.  Again, if none of the times offered through Blackboard work, then please email me.

Even though checking the type may be useful to you, returning <class 'str'> and <class 'list'> was not desired in the output.  Furthermore, you print out "This file is read only and cannot be modified" twice in your output.  That information is not requested.  Be sure to comment out non-required lines after you gather the data you might need.  
The explanation for len() in #2 is not accurate, and I don't see explanations of when you would use those different read functions.

I am intrigued in #2 that you would use splitlines() which was not introduced in the lesson (instead of using a read function different than read() that you used in the top one).  This was very industrious, and showed that you thought outside of the box.

The third did not adhere to reading one line at a time save the entire contents to a variable.

Thanks.

Chris

**Comment by cethenmc** [comment]
Locked in current grade and closed ticket.
