### ISSUE TITLE
midterm-slicing.py ready for grading

### ISSUE THREAD

**Issue by bmiller11-matc** [madisoncollege-it-programs/python-scripting-bmiller11-matc#9]

**Comment by cethenmc** [comment]
Midterm-slicing:  Nice work researching the string module for splitlines().  Your positive slicing is 'off' because you did your readline in a for loop.  The point of the for loop ends up completely unnecessary (1 pt).  In fact, it removes the word happy that you turn into your file variable.  Everything else is super well done.  33/34
